name: vitiscan_streamlit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - python-dotenv
  - requests
  - numpy
  - pandas
  - plotly
  - altair=4.2.2
  - ipykernel 
  - notebook
  - nbformat
  - glom
  - conda-bash-completion
  - streamlit
  - folium
  - pillow
  - streamlit-folium
  - protobuf=3.20.3
  #- geopy
  #- boto3
  #- s3fs
  #- pip:
  #  - -r file:env_streamlit_requirements.txt
