name: vitiscan_streamlit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit==1.45.0
    - folium==0.19.5
    - streamlit-folium==0.25.0
    - pillow==11.2.1
    - requests==2.32.3
    - python-dotenv==1.0.1
